In [2]:
import pandas as pd

dataframe = pd.read_csv('big_data.csv')

print(dataframe)

    EmployeeID     Name Department           City  Age Gender  \
0         1001    Rahul         IT        Seattle   25      M
1         1002     Alex         HR       New York   30      M
2         1003     Sara    Finance        Chicago   28      F
3         1004     John         IT        Seattle   35      M
4         1005    Emily         HR         Boston   29      F
5         1006    David    Finance        Chicago   40      M
6         1007     Nina         IT  San Francisco   27      F
7         1008      Tom  Marketing       New York   29      M
8         1009    Linda  Marketing         Boston   33      F
9         1010    Chris         IT        Seattle   31      M
10        1011    Arjun    Finance         Dallas   26      M
11        1012    Priya         IT         Austin   28      F
12        1013  Michael      Sales        Chicago   34      M
13        1014    Anita         HR        Seattle   41      F
14        1015   Robert      Sales         Dallas   37      M
15        1016   Sophia  Marketing  San Francisco   26      F
16        1017   Daniel         IT       New York   39      M
17        1018    Meena    Finance         Austin   32      F
18        1019    Kevin      Sales         Boston   29      M
19        1020    Pooja         IT        Seattle   24      F
20        1021   Andrew         HR        Chicago   36      M
21        1022    Kiran    Finance       San Jose   34      M
22        1023  Jessica  Marketing         Austin   31      F
23        1024   Ramesh      Sales  San Francisco   42      M
24        1025    Laura         IT         Boston   27      F

    ExperienceYears  Salary  PerformanceScore    JoinDate Attrition
0                 2   70000               3.8  2023-06-15        No
1                 5   60000               3.2  2021-03-10        No
2                 4   65000               3.5  2022-01-20        No
3                10   90000               4.5  2018-08-05        No
4                 3   58000               3.1  2022-11-01       Yes
5                15  110000               4.7  2015-05-18        No
6                 3   72000               3.9  2023-02-12        No
7                 4   55000               2.8  2021-09-25       Yes
8                 7   62000               3.4  2019-04-14        No
9                 6   80000               4.0  2020-07-30        No
10                2   63000               3.6  2023-01-10        No
11                4   75000               4.1  2021-12-05        No
12                8   68000               3.0  2019-06-22       Yes
13               15   88000               4.6  2014-02-17        No
14               12   72000               3.3  2016-09-01        No
15                2   56000               3.7  2023-05-08        No
16               14   98000               4.8  2012-11-11        No
17                9   83000               4.2  2018-03-19        No
18                5   66000               3.1  2020-10-27       Yes
19                1   65000               3.9  2024-01-05        No
20               11   77000               4.0  2016-04-23        No
21               10   90000               4.4  2017-08-14        No
22                6   61000               3.5  2019-12-30        No
23               18   88000               4.1  2010-07-07        No
24                3   71000               3.8  2022-06-18        No

In [4]:
dataframe.head()

,EmployeeID,Name,Department,City,Age,Gender,ExperienceYears,Salary,PerformanceScore,JoinDate,Attrition
0,1001,Rahul,IT,Seattle,25,M,2,70000,3.8,2023-06-15,No
1,1002,Alex,HR,New York,30,M,5,60000,3.2,2021-03-10,No
2,1003,Sara,Finance,Chicago,28,F,4,65000,3.5,2022-01-20,No
3,1004,John,IT,Seattle,35,M,10,90000,4.5,2018-08-05,No
4,1005,Emily,HR,Boston,29,F,3,58000,3.1,2022-11-01,Yes

In [5]:
dataframe.tail()

,EmployeeID,Name,Department,City,Age,Gender,ExperienceYears,Salary,PerformanceScore,JoinDate,Attrition
20,1021,Andrew,HR,Chicago,36,M,11,77000,4.0,2016-04-23,No
21,1022,Kiran,Finance,San Jose,34,M,10,90000,4.4,2017-08-14,No
22,1023,Jessica,Marketing,Austin,31,F,6,61000,3.5,2019-12-30,No
23,1024,Ramesh,Sales,San Francisco,42,M,18,88000,4.1,2010-07-07,No
24,1025,Laura,IT,Boston,27,F,3,71000,3.8,2022-06-18,No

In [6]:
dataframe.describe()

,EmployeeID,Age,ExperienceYears,Salary,PerformanceScore
count,25.000000,25.000000,25.000000,25.000000,25.000000
mean,1013.000000,31.720000,7.160000,73720.000000,3.800000
std,7.359801,5.208327,4.819059,14093.497319,0.553775
min,1001.000000,24.000000,1.000000,55000.000000,2.800000
25%,1007.000000,28.000000,3.000000,63000.000000,3.400000
50%,1013.000000,31.000000,6.000000,71000.000000,3.800000
75%,1019.000000,35.000000,10.000000,83000.000000,4.100000
max,1025.000000,42.000000,18.000000,110000.000000,4.800000

In [7]:
dataframe.head()

,EmployeeID,Name,Department,City,Age,Gender,ExperienceYears,Salary,PerformanceScore,JoinDate,Attrition
0,1001,Rahul,IT,Seattle,25,M,2,70000,3.8,2023-06-15,No
1,1002,Alex,HR,New York,30,M,5,60000,3.2,2021-03-10,No
2,1003,Sara,Finance,Chicago,28,F,4,65000,3.5,2022-01-20,No
3,1004,John,IT,Seattle,35,M,10,90000,4.5,2018-08-05,No
4,1005,Emily,HR,Boston,29,F,3,58000,3.1,2022-11-01,Yes

In [18]:
dataframe.iloc[0]

EmployeeID                1001
Name                     Rahul
Department                  IT
City                   Seattle
Age                         25
Gender                       M
ExperienceYears              2
Salary                   70000
PerformanceScore           3.8
JoinDate            2023-06-15
Attrition                   No
Name: 0, dtype: object

In [17]:
dataframe.loc[0]

EmployeeID                1001
Name                     Rahul
Department                  IT
City                   Seattle
Age                         25
Gender                       M
ExperienceYears              2
Salary                   70000
PerformanceScore           3.8
JoinDate            2023-06-15
Attrition                   No
Name: 0, dtype: object

In [20]:
### To find the datatype of the data

dataframe.dtypes

EmployeeID            int64
Name                    str
Department              str
City                    str
Age                   int64
Gender                  str
ExperienceYears       int64
Salary                int64
PerformanceScore    float64
JoinDate                str
Attrition               str
dtype: object

In [27]:
### Handling missing values

dataframe.isnull().any(axis=0)

### axis = 0
# Column-wise operation
# Moves down the rows
# Works on each column

### axis = 1
# Row-wise operation
# Moves across the columns
# Works on each row

EmployeeID          False
Name                False
Department          False
City                False
Age                 False
Gender              False
ExperienceYears     False
Salary              False
PerformanceScore    False
JoinDate            False
Attrition           False
dtype: bool

In [29]:
### Filling missing values with the mean of the column
import pandas as pd

dataframe2 = pd.read_csv('missing_data.csv')

dataframe2

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,PerformanceScore
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1
5,2006,David,Finance,40.0,110000.0,15.0,NaN,2015-05-18,4.7
6,2007,Nina,IT,27.0,72000.0,3.0,San Francisco,NaN,3.9
7,2008,Tom,Marketing,29.0,55000.0,4.0,New York,2021-09-25,2.8
8,2009,Linda,Marketing,NaN,62000.0,7.0,Boston,2019-04-14,NaN
9,2010,Chris,IT,31.0,80000.0,6.0,Seattle,2020-07-30,4.0

In [30]:
dataframe2.isnull()

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,PerformanceScore
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True
2,False,False,False,True,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,False
5,False,False,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False,True
9,False,False,False,False,False,False,False,False,False

In [32]:
dataframe2.isnull().any(axis=0)

EmployeeID          False
Name                False
Department          False
Age                  True
Salary               True
ExperienceYears      True
City                 True
JoinDate             True
PerformanceScore     True
dtype: bool

In [33]:
dataframe2['avg_Value'] = dataframe2['Salary'].fillna(dataframe2['Salary'].mean())

In [34]:
dataframe2.isnull().any(axis=0)

EmployeeID          False
Name                False
Department          False
Age                  True
Salary               True
ExperienceYears      True
City                 True
JoinDate             True
PerformanceScore     True
avg_Value           False
dtype: bool

In [35]:
dataframe2

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,PerformanceScore,avg_Value
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8,70000.000000
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN,60000.000000
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5,65000.000000
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5,70222.222222
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1,58000.000000
5,2006,David,Finance,40.0,110000.0,15.0,NaN,2015-05-18,4.7,110000.000000
6,2007,Nina,IT,27.0,72000.0,3.0,San Francisco,NaN,3.9,72000.000000
7,2008,Tom,Marketing,29.0,55000.0,4.0,New York,2021-09-25,2.8,55000.000000
8,2009,Linda,Marketing,NaN,62000.0,7.0,Boston,2019-04-14,NaN,62000.000000
9,2010,Chris,IT,31.0,80000.0,6.0,Seattle,2020-07-30,4.0,80000.000000

In [39]:
### Reraming Columns

dataframe2 = dataframe2.rename(columns={'PerformanceScore':'overAll_Score'})

dataframe2.head()

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,overAll_Score,avg_Value
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8,70000.000000
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN,60000.000000
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5,65000.000000
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5,70222.222222
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1,58000.000000

In [43]:
### change the datatypes

dataframe2.dtypes
dataframe2.isnull().any(axis=0)

EmployeeID         False
Name               False
Department         False
Age                 True
Salary              True
ExperienceYears     True
City                True
JoinDate            True
overAll_Score       True
avg_Value          False
dtype: bool

In [46]:
### changing the datatype

dataframe2['Age_int'] = dataframe2['Age'].fillna(dataframe2['Age'].mean()).astype(int)

dataframe2

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,overAll_Score,avg_Value,Age_int
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8,70000.000000,25
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN,60000.000000,30
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5,65000.000000,30
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5,70222.222222,35
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1,58000.000000,29
5,2006,David,Finance,40.0,110000.0,15.0,NaN,2015-05-18,4.7,110000.000000,40
6,2007,Nina,IT,27.0,72000.0,3.0,San Francisco,NaN,3.9,72000.000000,27
7,2008,Tom,Marketing,29.0,55000.0,4.0,New York,2021-09-25,2.8,55000.000000,29
8,2009,Linda,Marketing,NaN,62000.0,7.0,Boston,2019-04-14,NaN,62000.000000,30
9,2010,Chris,IT,31.0,80000.0,6.0,Seattle,2020-07-30,4.0,80000.000000,31

In [47]:
### changing the values using lambda functuon
### lets say salary has been increased

dataframe2['New_Salary'] = dataframe2['Salary'].apply(lambda x : x*2)

In [48]:
dataframe2.head()

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,overAll_Score,avg_Value,Age_int,New_Salary
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8,70000.000000,25,140000.0
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN,60000.000000,30,120000.0
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5,65000.000000,30,130000.0
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5,70222.222222,35,NaN
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1,58000.000000,29,116000.0