In [1]:
import pandas as np

dataframe = np.read_csv('missing_data.csv')

dataframe

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,PerformanceScore
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1
5,2006,David,Finance,40.0,110000.0,15.0,NaN,2015-05-18,4.7
6,2007,Nina,IT,27.0,72000.0,3.0,San Francisco,NaN,3.9
7,2008,Tom,Marketing,29.0,55000.0,4.0,New York,2021-09-25,2.8
8,2009,Linda,Marketing,NaN,62000.0,7.0,Boston,2019-04-14,NaN
9,2010,Chris,IT,31.0,80000.0,6.0,Seattle,2020-07-30,4.0

In [ ]:
### Data Grouping = Grouping means splitting data into categories based on a column.

### Data Aggregation = Aggregation means applying a summary function to each group.

In [2]:
dataframe.head()

,EmployeeID,Name,Department,Age,Salary,ExperienceYears,City,JoinDate,PerformanceScore
0,2001,Rahul,IT,25.0,70000.0,2.0,Seattle,2023-06-15,3.8
1,2002,Alex,HR,30.0,60000.0,5.0,New York,2021-03-10,NaN
2,2003,Sara,Finance,NaN,65000.0,4.0,Chicago,2022-01-20,3.5
3,2004,John,IT,35.0,NaN,10.0,Seattle,2018-08-05,4.5
4,2005,Emily,HR,29.0,58000.0,NaN,Boston,2022-11-01,3.1

In [7]:
### now based on salary column i want to do affregation and grouping

grouped_mean = dataframe.groupby('Salary')['ExperienceYears'].mean()

print(grouped_mean)

Salary
55000.0      4.0
58000.0      NaN
60000.0      5.0
62000.0      7.0
65000.0      4.0
70000.0      2.0
72000.0      3.0
80000.0      6.0
110000.0    15.0
Name: ExperienceYears, dtype: float64

In [9]:
### we can also group by more than 1 columns using a list

list_groupby = dataframe.groupby(['Department','ExperienceYears'])['Salary'].mean()

print(list_groupby)

Department  ExperienceYears
Finance     4.0                 65000.0
            15.0               110000.0
HR          5.0                 60000.0
IT          2.0                 70000.0
            3.0                 72000.0
            6.0                 80000.0
            10.0                    NaN
Marketing   4.0                 55000.0
            7.0                 62000.0
Name: Salary, dtype: float64

In [10]:
### Now aggregating multiple functions

aggre = dataframe.groupby('Department')['Salary'].agg(['mean','sum','count'])

print(aggre)

               mean       sum  count
Department
Finance     87500.0  175000.0      2
HR          59000.0  118000.0      2
IT          74000.0  222000.0      3
Marketing   58500.0  117000.0      2